In [1]:
import pandas as pd
# Gensim
import gensim
import gensim.corpora as corpora
import en_core_web_sm
import time
import nltk
from gensim.parsing.preprocessing import strip_punctuation, strip_tags, strip_numeric
from nltk.stem.wordnet import WordNetLemmatizer   
from nltk.corpus import stopwords
import spacy
nltk.download('wordnet')
#pip install spacy==1.8.2
#run the below command prompt navigating to the path to your packages-> 
#python -m spacy download en 
#after running the command, you should be able to run nlp=spacy.load("en_core_web_sm") to load the english lang. vocab
nlp = spacy.load("en_core_web_sm")
#nlp = en_core_web_sm.load()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\AG89382\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [2]:
'''
1. Get the scrapped Zomato and Swiggy Datasets during, before and after the incidence date.
2. Extract Article content for topic modelling
'''

'\n1. Get the scrapped Zomato and Swiggy Datasets during, before and after the incidence date.\n2. Extract Article content for topic modelling\n'

In [3]:
time.sleep(2)
start_time = time.time()
'''Read Scrapped Article files - '''
data0 = pd.read_csv('C:/.../Swiggy-Zomato-Food-Aggregators-Analysis/articles_data/Zomato_Articles.csv')
data0 = data0.dropna()
data00 = pd.read_csv('C:/.../Swiggy-Zomato-Food-Aggregators-Analysis/articles_data/Swiggy_Articles.csv') 
data00 = data00.dropna()


#Zomato -
Zomato_data_during_incidence = data0[data0.Article_date.str.contains('11 December 2018',case=False)]
print("\nZomato Data- During Incidence:")
display(Zomato_data_during_incidence)

Zomato_data_after_incidence = data0.loc[:(Zomato_data_during_incidence.index.values[0]-1)]
print("\nZomato Data- After Incidence:")
display(Zomato_data_after_incidence)

Zomato_data_before_incidence = data0.loc[(Zomato_data_during_incidence.index.values[0]+1):]
print("\nZomato Data- Before Incidence:")
display(Zomato_data_before_incidence)


#Swiggy -
Swiggy_data_during_incidence = data00[data00.Article_date.str.contains('26 July 2017',case=False)]
print("\nSwiggy Data- During Incidence:")
display(Swiggy_data_during_incidence)
Swiggy_data_after_incidence = data00.loc[:(Swiggy_data_during_incidence.index.values[0]-1)]
print("\nSwiggy Data- After Incidence:")
display(Swiggy_data_after_incidence)
Swiggy_data_before_incidence = data00.loc[(Swiggy_data_during_incidence.index.values[0]+1):]
print("\nSwiggy Data- Before Incidence:")
display(Swiggy_data_before_incidence)

Zomato Data- During Incidence:

,Article_title,Article_date,Article_content
12,Zomato Responds to Viral Video Showing Its Del...,Updated: 11 December 2018 13:18 IST,While food ordering platform Zomato is on a sp...

Zomato Data- After Incidence:

,Article_title,Article_date,Article_content
0,Zomato Successfully Tests Its Drone Technology...,Updated: 13 June 2019 10:09 IST,"Zomato, the online ordering and food delivery ..."
1,"Zomato Expands to 100 New Cities in India, Cro...",Updated: 4 June 2019 12:05 IST,"Crossing the 300-cities mark, online ordering ..."
2,Will India Have 100 Internet Unicorns by 2025?...,Updated: 3 May 2019 18:48 IST,India is on track to have between 750 million ...
3,"Zomato's Hyperpure Launched in Delhi, Eyes 22 ...",Updated: 29 April 2019 18:12 IST,Food ordering app Zomato on Monday announced t...
4,"Zomato Expands Online Ordering, Food Delivery ...",Updated: 2 April 2019 16:19 IST,Food ordering app Zomato on Monday announced a...
5,Zomato Introduces 'Tamper-Proof Packaging' In ...,Updated: 21 March 2019 15:03 IST,"In December last year, a viral video of a Zoma..."
6,'Paytm First' Subscription Launched at Rs. 750...,Updated: 5 March 2019 16:45 IST,Paytm First subscription-based loyalty program...
7,App-Based Delivery Men Highlight India's Growi...,Updated: 20 February 2019 17:03 IST,Suraj Nachre works long hours and regularly mi...
8,Zomato Says Working With Restaurant Partners t...,Updated: 12 February 2019 17:38 IST,With hundreds of restaurant owners sending a p...
10,Paytm Partners With Zomato to Add Food Orderin...,Updated: 17 January 2019 14:18 IST,Paytm now lets you order food through its app....
11,"Zomato Announces Food Carnival 'Zomaland', to ...",Updated: 27 December 2018 17:49 IST,Zomato is going to organise a food carnival ca...

Zomato Data- Before Incidence:

,Article_title,Article_date,Article_content
13,Zomato Buys Lucknow-Based TechEagle to Build T...,Updated: 5 December 2018 18:43 IST,With an aim to deliver food via drones in Indi...
14,"Zomato to Bring Online Ordering, Food Delivery...",Updated: 30 November 2018 19:07 IST,Zomato on Friday announced that it will launch...
15,App Store Diwali Offers Include Deals on Canva...,Updated: 5 November 2018 18:58 IST,Diwali 2018 is just around the corner and Appl...
16,Zomato Is Raising $210 Million From Alibaba’s ...,Updated: 15 October 2018 11:57 IST,Zomato has signed a definitive agreement to ra...
17,FreshMenu 2016 Data Breach Reportedly Exposed ...,Updated: 11 September 2018 13:04 IST,Food delivery provider FreshMenu started opera...
18,Zomato Acquires Bengaluru Startup TongueStun t...,Updated: 5 September 2018 18:56 IST,Food-ordering app Zomato has announced that it...
19,"Kerala Floods: What Google, Facebook, Amazon, ...",Updated: 20 August 2018 19:39 IST,Kerala floods have ravaged thousands of homes ...
20,"Zomato Strengthens Presence in Tier II, Expand...",Updated: 10 August 2018 18:40 IST,Online food delivery platform Zomato on Friday...
21,Swiggy Super Is a Paid Subscription Programme ...,Updated: 31 July 2018 12:35 IST,"Swiggy, one of India's largest food ordering a..."
22,Zomato Piggybank Reward Points Programme Launc...,Updated: 10 July 2018 12:21 IST,Food ordering and restaurant search app Zomato...
23,Zomato Launches Operations in 25 New Cities in...,Updated: 27 June 2018 13:51 IST,Food ordering app Zomato on Wednesday said it ...
24,"Zomato Adds Short Bio for Delivery Executives,...",Updated: 25 June 2018 18:46 IST,Zomato will now show a short biography of the ...
25,"Zomato Gold to Become Invite-Only, Public Purc...",Updated: 26 April 2018 18:50 IST,"As a result of the overwhelming response, Zoma..."
26,"For Both Customers and Restaurants, the Likes ...",Updated: 5 April 2018 17:09 IST,"A few years ago, people were starting to write..."
27,Zomato Announces $150 Million in Funding From ...,Updated: 1 March 2018 12:44 IST,A unit of China's Alibaba Group Holding has in...
28,Swiggy Has Raised $100 Million in Funding From...,Updated: 8 February 2018 14:36 IST,Swiggy on Thursday announced Series F funding ...
29,"From Food to Streaming, We Need Aggregators fo...",Updated: 9 January 2018 16:32 IST,Having choice is a good thing. That applies to...
30,"WhatsApp 'Delete for Everyone' Loophole, UC Br...",Updated: 15 November 2017 22:42 IST,The WhatsApp delete for everyone feature that ...
31,Zomato Gold Premium Subscription Comes to Indi...,Updated: 15 November 2017 15:53 IST,Hoping to boost engagement from Indian foodies...
32,"WhatsApp Message Delete Feature, Pixel 2 on Sa...",Updated: 1 November 2017 21:22 IST,WhatsApp has rolled out the ‘Delete for Everyo...
33,Zomato Introduces Food Hygiene Ratings for Res...,Updated: 1 November 2017 11:23 IST,One of the worries that we sometimes have with...
34,"Jio Phone Deliveries Begin, Discounts on Samsu...",Updated: 25 September 2017 22:49 IST,Jio Phone deliveries have supposedly begun and...
35,Zomato Makes Investment in Hyderabad-Based Hom...,Updated: 25 September 2017 13:24 IST,Zomato said on Monday that it has made an inve...

Swiggy Data- During Incidence:

,Article_title,Article_date,Article_content
21,Swiggy Denies Claims by Supposed Ex-Employees ...,Updated: 26 July 2017 20:49 IST,"After hours of ""anxiety and confusion,"" online..."

Swiggy Data- After Incidence:

,Article_title,Article_date,Article_content
0,"Swiggy Daily App Launched for Homestyle Meals,...",Updated: 3 June 2019 15:10 IST,Homegrown food delivery start-up Swiggy on Mon...
1,Swiggy Says Delivers Over 1.5 Million Orders a...,Updated: 29 April 2019 16:52 IST,"Swiggy, domestic online food ordering and deli..."
2,App-Based Delivery Men Highlight India's Growi...,Updated: 20 February 2019 17:03 IST,Suraj Nachre works long hours and regularly mi...
3,Swiggy 'Stores' to Start Delivering Home Essen...,Updated: 12 February 2019 14:08 IST,Indian online food delivery service Swiggy sai...
4,Food Delivery Apps Bet Big on Artificial Intel...,Updated: 5 February 2019 17:58 IST,Driven by a surge in online food orders especi...
5,Swiggy Acqui-Hires Bengaluru-Based AI Startup ...,Updated: 4 February 2019 14:20 IST,Online food ordering and delivery app Swiggy o...
6,Swiggy Raises $1 Billion in Naspers-Led Fundin...,Updated: 20 December 2018 15:48 IST,Online food delivery service provider Swiggy s...
7,App Store Diwali Offers Include Deals on Canva...,Updated: 5 November 2018 18:58 IST,Diwali 2018 is just around the corner and Appl...
8,Swiggy Launches Operations in 8 More Cities,Updated: 24 September 2018 18:39 IST,"Food ordering and delivery platform, Swiggy on..."
9,Swiggy Confirms Acquisition of On-Demand Deliv...,Updated: 2 August 2018 14:31 IST,Indian online food ordering and delivery platf...
10,Swiggy Super Is a Paid Subscription Programme ...,Updated: 31 July 2018 12:35 IST,"Swiggy, one of India's largest food ordering a..."
11,Swiggy Appoints Vivek Sunder as Chief Operatin...,Updated: 2 July 2018 16:35 IST,Swiggy on Monday announced appointment of Vive...
12,Swiggy Announces $210 Million in Funding From ...,Updated: 21 June 2018 13:51 IST,Swiggy on Thursday announced Series G funding ...
13,"For Both Customers and Restaurants, the Likes ...",Updated: 5 April 2018 17:09 IST,"A few years ago, people were starting to write..."
14,Zomato Announces $150 Million in Funding From ...,Updated: 1 March 2018 12:44 IST,A unit of China's Alibaba Group Holding has in...
15,Swiggy Has Raised $100 Million in Funding From...,Updated: 8 February 2018 14:36 IST,Swiggy on Thursday announced Series F funding ...
16,"From Food to Streaming, We Need Aggregators fo...",Updated: 9 January 2018 16:32 IST,Having choice is a good thing. That applies to...
17,"Swiggy Access Launched, Ready-to-Occupy Kitche...",Updated: 14 November 2017 17:15 IST,Online food ordering and delivery platform Swi...
18,"Zomato Completes Runnr Acquisition, Will Conti...",Updated: 14 September 2017 12:16 IST,Zomato on Wednesday announced that it has comp...
19,"FreshMenu Believes Content Can Drive Sales, Sa...",Updated: 2 August 2017 09:41 IST,Food delivery has seen its ups and downs over ...
20,How Swiggy Revamped Its Tech to Speed Up Deliv...,Updated: 28 July 2017 11:10 IST,"For companies that deliver your food, every se..."

Swiggy Data- Before Incidence:

,Article_title,Article_date,Article_content
22,"OnePlus 5 Release Date Leak, Essential Phone F...",Updated: 30 May 2017 21:48 IST,"Another day, another OnePlus 5 leak. This time..."
23,"Swiggy Raises $80 Million From Naspers, Existi...",Updated: 30 May 2017 15:52 IST,Online food delivery platform Swiggy on Tuesda...
24,Swiggy Joins Google Local Guides to Share Rest...,Updated: 2 May 2017 17:12 IST,Food ordering and delivery service Swiggy on T...
25,Cloud Kitchens Take the Risk Out of Trying New...,Updated: 27 January 2017 14:13 IST,Online food delivery is a tricky business and ...
26,Meet the Indian Startups Vying to Be the Swigg...,Updated: 11 January 2017 16:30 IST,"Around 18 months ago, a slew of fitness wearab..."
27,"500 Rs. Note Gone, Amazon Disables Cash on Del...",Updated: 10 November 2016 14:35 IST,The demonetisation of 1000 Rs. and 500 Rs. not...
28,Swiggy Ropes in Myntra Co-Founder Mukesh Bansa...,Updated: 5 October 2016 18:19 IST,Food delivery platform Swiggy has appointed My...
29,Foodpanda India CEO on New 'Hygiene Rating' fo...,Updated: 31 August 2016 12:23 IST,One of the plus points of using a food deliver...
30,Apps That Make Hanging Out With Friends a Lot ...,Updated: 13 September 2016 17:36 IST,We've all been there - you start off with some...
31,"Google Now Lets You Order Food, Book a Table F...",Updated: 9 August 2016 13:15 IST,There might be many who have started using opt...
32,"India Funding Roundup: Swiggy, Jugnoo, Industr...",Updated: 27 January 2016 17:37 IST,Funding activity seems to have increased in th...
33,'Restaurant OS' Will Talk to All Food Tech Sta...,Updated: 8 October 2015 10:55 IST,The food-tech industry is an increasingly comp...

In [4]:
def gensimmod(data, article_name):
    
    '''
    
    This function runs the LDA model and returns two output - 
    - output1 gives us the count of topics in which a particular document falls into. It has below variables:
        [cnt_of_topics_doc_appeared", "documents", "tokens"]
        
    - output2 gives us the percentage contribution along with the dominant topic in which a particular document falls in.
    That is to say, some documents are associated with multiple topics and have certain contribution in them. 
    The output here gives us the topic to why they are most associated with. 
    Column names in output2:-
    ['Doc_num', 'Dominant_Topic', 'Perc_Contribution', 'Topic_Keywords', 'orig_contents']
    
    '''

    
    'Extract Article content for topic modelling'
    reviews = data['Article_content']  # Extract Article content for topic modelling
    reviews = list(reviews)
    
    'Import WordNet Lemmatizer to lemmatize documents'
    lemma = WordNetLemmatizer()
    stop_words = stopwords.words('english')
    
    'User Named Entity Recognition from Spacy Module and get entities names, such as person, apartment, place etc'
    labels11 = ['Token', ' IOB', 'Entity']
    ner = pd.DataFrame()
    for i in range(0, len(reviews)):
        doc_1 = nlp(reviews[i]) # use nlp() from spacy module
        ner_1 = pd.DataFrame([(X, X.ent_iob_, X.ent_type_) for X in doc_1], columns = labels11)
        ner_1['doc_num'] = i
        ner = ner.append(ner_1) # Store entities in ner dataframe
        
    WordstoExclude = ner_1.loc[ner_1['Entity'] == 'ORG']  # ORG, organisation
    excludewords = WordstoExclude.Token
    excludewords = [str(i).lower() for i in excludewords]
    
    words = [] 
    for i in excludewords:
        if not i in words:
            words.append(i);
    
    
    'text cleaning of articles data'
    stop_words.extend(words) # Extending stop words list by adding Named Entity = ORG to it.
    stop_words.extend(['said', 'r', 'delivery', 'get', 'crore', 'company', 'rathi', 'say'])
    #Clean Text 
    def textClean(text0):
        text1 = [strip_punctuation(doc) for doc in text0]
        text1 = [strip_tags(doc) for doc in text1]
        text1 = [strip_numeric(doc) for doc in text1]
        text1 = [[" ".join([i for i in doc.lower().split() if i not in stop_words])] for doc in text1]
        #text2 = [[word for word in ' '.join(doc).split()] for doc in text1]
        normalized = [[" ".join([lemma.lemmatize(word) for word in ' '.join(doc).split()])] for doc in text1]
        return normalized
    
    corpus1 = textClean(reviews)  # Cleaned corpus .
    
    'word tokenization in corpus' 
    corpus11 = [[word for word in ' '.join(doc).split()] for doc in corpus1]  # word_tokenize 
    #corpus11[1]
    
    
    'Create Dictionary and Corpus required for LDA as inputs'
    id2word = corpora.Dictionary(corpus11)  # Create Dictionary
    corpus = [id2word.doc2bow(text) for text in corpus11]  # Building gensim corpus. TF DTM creation.
    #print(corpus[:1])  # View one doc in abstract form
    #id2word[2]
    
    
    '''
    A topic model is a sort of probabilistic generative model to find the representative topic of a document/corpus which 
    in our case , we are using latent Dirichlet allocation (LDA) technique to find the topics to which
    a document most suits to. 
    '''
    
    '''Build LDA model for K=5 topics '''
    lda_model = gensim.models.ldamodel.LdaModel(corpus=corpus,
                                               id2word=id2word,
                                               num_topics=5, 
                                               random_state=100, # similar to set.seed() so that results does not change 
                                               update_every=1, # update corpus after each pass
                                               chunksize=8, # earlier chunksize = 7 and num_topics = 5
                                               passes=100,  # 100 passes taking 8 samples(chunksize) in each iteration
                                               alpha='auto',
                                               per_word_topics=False)
    
    print("\nLDA Model topics output from Corpus[Latent Dirichlet Allocation Method] for:" + article_name + "\n")
    display(lda_model.print_topics())
    
    ''' Beta and Gamma Factor matrices - tokens to topics mapping, document to topics mapping respectively'''
    ## obtain the factor matrices - beta
    def build_beta_df(lda_model=lda_model, id2word=id2word):
        beta = lda_model.get_topics()  # shape (num of topics, vocabulary size).
        beta_df = pd.DataFrame(data=beta)
    
        # convert colnames in beta_df 2 tokens
        token2col = list(id2word.token2id)
        beta_df.columns = token2col
        rowNames=['topic' + format(x+1, '02d') for x in range(beta_df.shape[0])]
        rowNames_series = pd.Series(rowNames)
        beta_df.rename(index=rowNames_series, inplace=True)
        return(beta_df)
    
    #document to topics mapping respectively
    def build_gamma_df(lda_model, corpus0):
        gamma_doc = []  
        num_topics = lda_model.get_topics().shape[0]
        
        for doc in range(len(corpus0)):
            doc1 = corpus0[doc].split()
            bow_doc = id2word.doc2bow(doc1)
            gamma_doc0 = [0]*num_topics  
            gamma_doc1 = lda_model.get_document_topics(bow_doc)
            gamma_doc2_x = [x for (x,y) in gamma_doc1]
            gamma_doc2_y = [y for (x,y) in gamma_doc1]
            for i in range(len(gamma_doc1)):
                x = gamma_doc2_x[i]
                y = gamma_doc2_y[i]
                gamma_doc0[x] = y  
            gamma_doc.append(gamma_doc0)
            
        gamma_df = pd.DataFrame(data=gamma_doc)  # shape=num_docs x num_topics
        topicNames=['topic' + format(x+1, '02d') for x in range(num_topics)]
        topicNames_series = pd.Series(topicNames)
        gamma_df.rename(columns=topicNames_series, inplace=True)
        return(gamma_df)
    
    
    # Apply build_gamma_df function to get gamma factor matrices.
    gamma_df = build_gamma_df(lda_model=lda_model, corpus0=reviews) 
    print("\nGamma Matrix for: " + article_name)
    time.sleep(2)
    display(gamma_df)
    #gamma_df.iloc[:36, :]     
    
    
    '''Fit Metrices ''' 
    '''Compute Perplexity'''
    #print('\nPerplexity: ', lda_model.log_perplexity(corpus))
    # Perplexity:  -7.375374126997931 
    #Lower the better.
    row0 = gamma_df.values.tolist()
    row=[]
    for i in range(len(row0)):
        row1 = list(enumerate(row0[i]))
        row1_y = [y for (x,y) in row1]
        max_propn = sorted(row1_y, reverse=True)[0]
        row2 = [(i, x+1, y) for (x, y) in row1 if y==max_propn]
        row.append(row2)
 
    occurence_count = (gamma_df != 0).astype(int).sum(axis=1)
    
    document_occ_cnt_in_topics = pd.DataFrame(reviews, occurence_count).reset_index()
    document_occ_cnt_in_topics['tokens'] = pd.Series(corpus11)
    document_occ_cnt_in_topics.columns = ["cnt_of_topics_doc_appeared", "documents", "tokens"]
    print("\nDocument Occurrence in Topics (A document in multiple topics) in: " + article_name)
    display(document_occ_cnt_in_topics)
    
    sent_topics_df = pd.DataFrame()
    for row1 in row:
        for (doc_num, topic_num, prop_topic) in row1:
            wp = lda_model.show_topic(topic_num-1)
            topic_keywords = ", ".join([word for word, prop in wp])
            sent_topics_df = sent_topics_df.append(pd.Series([int(doc_num), int(topic_num), 
                                                              round(prop_topic,4), 
                                                              topic_keywords]), 
                                                           ignore_index=True)
        
    sent_topics_df.columns = ['Doc_num', 'Dominant_Topic', 'Perc_Contribution', 'Topic_Keywords']  
    print("\nDocuments with dominant topic and its percentage contribution in: "+article_name)
    display(sent_topics_df)
    
    
    # Add original text to the end of the output
    contents = pd.Series(reviews)
    sent_topics_df = pd.concat([sent_topics_df, contents], axis=1)
    sent_topics_df.columns = ['Doc_num', 'Dominant_Topic', 'Perc_Contribution', 'Topic_Keywords', 'orig_contents']
    #sent_topics_df.to_excel("C:/.../<.xlsx file name>", sheet_name = "BeforeIncidence")  # doctest: +SKIP
    return document_occ_cnt_in_topics, sent_topics_df


loop = (Zomato_data_during_incidence.dropna(), Zomato_data_after_incidence.dropna(), 
        Zomato_data_before_incidence.dropna(), Swiggy_data_during_incidence.dropna(), 
        Swiggy_data_after_incidence.dropna(), Swiggy_data_before_incidence.dropna())


for i in range(0, len(loop)):
    j=("zoma_during_incdnt_topicmdl", "zoma_after_incdnt_topicmdl", "zoma_before_incdnt_topicmdl",
       "swgy_during_incdnt_topicmdl", "swgy_after_incdnt_topicmdl", "swgy_before_incdnt_topicmdl")
    #j = ["zoma_bigram_during_incdnt_topicmdl", "TopicModelling_After", "TopicModelling_Before", "TopicModelling_During", "TopicModelling_After", "TopicModelling_Before"]
    print("\n\n")
    display("Get Topic Modelling Results for-"+str(j[i]))
    results = gensimmod(loop[i], article_name=str(j[i]))
    dominant_documents = results[0]  # first result of the function gensimmod ->document_occ_cnt_in_topics 
    documents_to_topic_mapping = results[1]

    #if i<3:
    with pd.ExcelWriter("C:/.../Swiggy-Zomato-Food-Aggregators-Analysis/articles_data/lda_output/" + j[i] + ".xlsx") as writer:
        dominant_documents.to_excel(writer, sheet_name= 'dominant_documents')  
        documents_to_topic_mapping.to_excel(writer, sheet_name= 'documents_to_topics')

'Get Topic Modelling Results for-zoma_during_incdnt_topicmdl'

LDA Model topics output from Corpus[Latent Dirichlet Allocation Method] for:zoma_during_incdnt_topicmdl

[(0,
  '0.027*"food" + 0.027*"video" + 0.021*"also" + 0.017*"platform" + 0.011*"boxed" + 0.011*"via" + 0.011*"show" + 0.011*"—" + 0.011*"executive" + 0.011*"fleet"'),
 (1,
  '0.005*"process" + 0.005*"privacy" + 0.005*"putting" + 0.005*"public" + 0.005*"proof" + 0.005*"r" + 0.005*"post" + 0.005*"precautionary" + 0.005*"raised" + 0.005*"presence"'),
 (2,
  '0.005*"process" + 0.005*"privacy" + 0.005*"putting" + 0.005*"public" + 0.005*"proof" + 0.005*"r" + 0.005*"post" + 0.005*"precautionary" + 0.005*"raised" + 0.005*"presence"'),
 (3,
  '0.005*"process" + 0.005*"privacy" + 0.005*"putting" + 0.005*"public" + 0.005*"proof" + 0.005*"r" + 0.005*"post" + 0.005*"precautionary" + 0.005*"raised" + 0.005*"presence"'),
 (4,
  '0.005*"video" + 0.005*"also" + 0.005*"food" + 0.005*"public" + 0.005*"process" + 0.005*"question" + 0.005*"proof" + 0.005*"precautionary" + 0.005*"presence" + 0.005*"received"')]

Gamma Matrix for: zoma_during_incdnt_topicmdl

    topic01  topic02  topic03  topic04  topic05
0  0.999957        0        0        0        0

Document Occurrence in Topics (A document in multiple topics) in: zoma_during_incdnt_topicmdl

,cnt_of_topics_doc_appeared,documents,tokens
0,1,While food ordering platform Zomato is on a sp...,"[food, ordering, platform, spree, expanding, m..."

Documents with dominant topic and its percentage contribution in: zoma_during_incdnt_topicmdl

,Doc_num,Dominant_Topic,Perc_Contribution,Topic_Keywords
0,0.0,1.0,1.0,"food, video, also, platform, boxed, via, show,..."

'Get Topic Modelling Results for-zoma_after_incdnt_topicmdl'

LDA Model topics output from Corpus[Latent Dirichlet Allocation Method] for:zoma_after_incdnt_topicmdl

[(0,
  '0.029*"restaurant" + 0.016*"food" + 0.015*"partner" + 0.010*"discounting" + 0.009*"kitchen" + 0.008*"india" + 0.008*"company" + 0.008*"petition" + 0.008*"spokesperson" + 0.007*"growth"'),
 (1,
  '0.016*"drone" + 0.013*"food" + 0.007*"packaging" + 0.006*"restaurant" + 0.006*"time" + 0.006*"safety" + 0.006*"tamper" + 0.006*"proof" + 0.005*"wing" + 0.005*"test"'),
 (2,
  '0.021*"food" + 0.019*"city" + 0.011*"carnival" + 0.008*"feature" + 0.008*"india" + 0.007*"well" + 0.007*"statement" + 0.007*"delhi" + 0.007*"move" + 0.006*"gupta"'),
 (3,
  '0.020*"startup" + 0.017*"india" + 0.011*"indian" + 0.009*"market" + 0.009*"year" + 0.008*"say" + 0.008*"government" + 0.007*"internet" + 0.006*"ecosystem" + 0.006*"investor"'),
 (4,
  '0.039*"paytm" + 0.031*"food" + 0.022*"ordering" + 0.019*"city" + 0.018*"customer" + 0.018*"app" + 0.014*"also" + 0.012*"service" + 0.011*"india" + 0.011*"platform"')]

Gamma Matrix for: zoma_after_incdnt_topicmdl

     topic01   topic02   topic03   topic04   topic05
0   0.000000  0.999609  0.000000  0.000000  0.000000
1   0.000000  0.055200  0.480144  0.130686  0.333683
2   0.000000  0.000000  0.000000  0.999887  0.000000
3   0.016827  0.000000  0.982635  0.000000  0.000000
4   0.589490  0.055563  0.000000  0.000000  0.354618
5   0.000000  0.874276  0.000000  0.000000  0.125421
6   0.011258  0.000000  0.000000  0.000000  0.988451
7   0.000000  0.038121  0.000000  0.887012  0.074750
8   0.968296  0.031312  0.000000  0.000000  0.000000
9   0.000000  0.025671  0.000000  0.000000  0.974142
10  0.043585  0.000000  0.955864  0.000000  0.000000

Document Occurrence in Topics (A document in multiple topics) in: zoma_after_incdnt_topicmdl

,cnt_of_topics_doc_appeared,documents,tokens
0,1,"Zomato, the online ordering and food delivery ...","[online, ordering, food, platform, wednesday, ..."
1,4,"Crossing the 300-cities mark, online ordering ...","[crossing, city, mark, online, ordering, food,..."
2,1,India is on track to have between 750 million ...,"[india, track, million, million, people, using..."
3,2,Food ordering app Zomato on Monday announced t...,"[food, ordering, app, monday, announced, launc..."
4,3,Food ordering app Zomato on Monday announced a...,"[food, ordering, app, monday, announced, expan..."
5,2,"In December last year, a viral video of a Zoma...","[december, last, year, viral, video, executive..."
6,2,Paytm First subscription-based loyalty program...,"[paytm, first, subscription, based, loyalty, p..."
7,3,Suraj Nachre works long hours and regularly mi...,"[suraj, nachre, work, long, hour, regularly, m..."
8,2,With hundreds of restaurant owners sending a p...,"[hundred, restaurant, owner, sending, petition..."
9,2,Paytm now lets you order food through its app....,"[paytm, let, order, food, app, paytm, parent, ..."
10,2,Zomato is going to organise a food carnival ca...,"[going, organise, food, carnival, called, move..."

Documents with dominant topic and its percentage contribution in: zoma_after_incdnt_topicmdl

,Doc_num,Dominant_Topic,Perc_Contribution,Topic_Keywords
0,0.0,2.0,0.9996,"drone, food, packaging, restaurant, time, safe..."
1,1.0,3.0,0.4801,"food, city, carnival, feature, india, well, st..."
2,2.0,4.0,0.9999,"startup, india, indian, market, year, say, gov..."
3,3.0,3.0,0.9826,"food, city, carnival, feature, india, well, st..."
4,4.0,1.0,0.5895,"restaurant, food, partner, discounting, kitche..."
5,5.0,2.0,0.8743,"drone, food, packaging, restaurant, time, safe..."
6,6.0,5.0,0.9885,"paytm, food, ordering, city, customer, app, al..."
7,7.0,4.0,0.8870,"startup, india, indian, market, year, say, gov..."
8,8.0,1.0,0.9683,"restaurant, food, partner, discounting, kitche..."
9,9.0,5.0,0.9741,"paytm, food, ordering, city, customer, app, al..."
10,10.0,3.0,0.9559,"food, city, carnival, feature, india, well, st..."

'Get Topic Modelling Results for-zoma_before_incdnt_topicmdl'

LDA Model topics output from Corpus[Latent Dirichlet Allocation Method] for:zoma_before_incdnt_topicmdl

[(0,
  '0.016*"user" + 0.014*"kerala" + 0.013*"piggybank" + 0.012*"flood" + 0.011*"help" + 0.010*"also" + 0.009*"donate" + 0.008*"google" + 0.007*"ngo" + 0.007*"code"'),
 (1,
  '0.019*"food" + 0.016*"restaurant" + 0.012*"hygiene" + 0.009*"like" + 0.008*"different" + 0.008*"platform" + 0.007*"rating" + 0.007*"order" + 0.007*"problem" + 0.007*"one"'),
 (2,
  '0.009*"menu" + 0.007*"invite" + 0.005*"club" + 0.003*"discerning" + 0.003*"debuted" + 0.003*"crawl" + 0.003*"persuade" + 0.003*"exciting" + 0.003*"arrived" + 0.003*"naturally"'),
 (3,
  '0.023*"food" + 0.013*"restaurant" + 0.010*"order" + 0.009*"india" + 0.009*"service" + 0.009*"user" + 0.009*"new" + 0.009*"city" + 0.008*"partner" + 0.008*"gold"'),
 (4,
  '0.018*"r" + 0.018*"gb" + 0.013*"india" + 0.009*"new" + 0.008*"₹" + 0.008*"phone" + 0.007*"app" + 0.007*"core" + 0.006*"percent" + 0.006*"offer"')]

Gamma Matrix for: zoma_before_incdnt_topicmdl

     topic01   topic02   topic03   topic04   topic05
0   0.000000  0.000000  0.000000  0.999510  0.000000
1   0.000000  0.000000  0.000000  0.999669  0.000000
2   0.000000  0.000000  0.000000  0.060507  0.939148
3   0.000000  0.000000  0.000000  0.999579  0.000000
4   0.000000  0.072644  0.000000  0.927233  0.000000
5   0.000000  0.000000  0.000000  0.999567  0.000000
6   0.999555  0.000000  0.000000  0.000000  0.000000
7   0.000000  0.000000  0.000000  0.999211  0.000000
8   0.000000  0.040082  0.000000  0.959658  0.000000
9   0.309580  0.064821  0.000000  0.625456  0.000000
10  0.000000  0.000000  0.000000  0.999531  0.000000
11  0.000000  0.000000  0.000000  0.999678  0.000000
12  0.000000  0.037345  0.210144  0.752253  0.000000
13  0.000000  0.815546  0.000000  0.184322  0.000000
14  0.000000  0.000000  0.000000  0.999673  0.000000
15  0.000000  0.000000  0.000000  0.999656  0.000000
16  0.000000  0.999166  0.000000  0.000000  0.000000
17  0.000000  0.000000  0.000000  0.057194  0.942723
18  0.000000  0.012089  0.000000  0.987634  0.000000
19  0.000000  0.000000  0.000000  0.195421  0.804458
20  0.000000  0.821755  0.000000  0.178052  0.000000
21  0.000000  0.000000  0.000000  0.144928  0.854995
22  0.000000  0.000000  0.000000  0.999375  0.000000

Document Occurrence in Topics (A document in multiple topics) in: zoma_before_incdnt_topicmdl

,cnt_of_topics_doc_appeared,documents,tokens
0,1,With an aim to deliver food via drones in Indi...,"[aim, deliver, food, via, drone, india, online..."
1,1,Zomato on Friday announced that it will launch...,"[friday, announced, launch, online, ordering, ..."
2,2,Diwali 2018 is just around the corner and Appl...,"[diwali, around, corner, apple, announced, off..."
3,1,Zomato has signed a definitive agreement to ra...,"[signed, definitive, agreement, raise, primary..."
4,2,Food delivery provider FreshMenu started opera...,"[food, provider, freshmenu, started, operation..."
5,1,Food-ordering app Zomato has announced that it...,"[food, ordering, app, announced, acquired, ton..."
6,1,Kerala floods have ravaged thousands of homes ...,"[kerala, flood, ravaged, thousand, home, kille..."
7,1,Online food delivery platform Zomato on Friday...,"[online, food, platform, friday, announced, ex..."
8,2,"Swiggy, one of India's largest food ordering a...","[one, india, largest, food, ordering, platform..."
9,3,Food ordering and restaurant search app Zomato...,"[food, ordering, restaurant, search, app, tues..."
10,1,Food ordering app Zomato on Wednesday said it ...,"[food, ordering, app, wednesday, launched, res..."
11,1,Zomato will now show a short biography of the ...,"[show, short, biography, executive, give, opti..."
12,3,"As a result of the overwhelming response, Zoma...","[result, overwhelming, response, gold, set, be..."
13,2,"A few years ago, people were starting to write...","[year, ago, people, starting, write, food, ind..."
14,1,A unit of China's Alibaba Group Holding has in...,"[unit, china, alibaba, group, holding, investe..."
15,1,Swiggy on Thursday announced Series F funding ...,"[thursday, announced, series, f, funding, exis..."
16,1,Having choice is a good thing. That applies to...,"[choice, good, thing, applies, everything, air..."
17,2,The WhatsApp delete for everyone feature that ...,"[whatsapp, delete, everyone, feature, released..."
18,2,Hoping to boost engagement from Indian foodies...,"[hoping, boost, engagement, indian, foodie, la..."
19,2,WhatsApp has rolled out the ‘Delete for Everyo...,"[whatsapp, rolled, ‘delete, everyone’, feature..."
20,2,One of the worries that we sometimes have with...,"[one, worry, sometimes, ordering, food, online..."
21,2,Jio Phone deliveries have supposedly begun and...,"[jio, phone, delivery, supposedly, begun, cust..."
22,1,Zomato said on Monday that it has made an inve...,"[monday, made, investment, hyderabad, based, s..."

Documents with dominant topic and its percentage contribution in: zoma_before_incdnt_topicmdl

,Doc_num,Dominant_Topic,Perc_Contribution,Topic_Keywords
0,0.0,4.0,0.9995,"food, restaurant, order, india, service, user,..."
1,1.0,4.0,0.9997,"food, restaurant, order, india, service, user,..."
2,2.0,5.0,0.9391,"r, gb, india, new, ₹, phone, app, core, percen..."
3,3.0,4.0,0.9996,"food, restaurant, order, india, service, user,..."
4,4.0,4.0,0.9272,"food, restaurant, order, india, service, user,..."
5,5.0,4.0,0.9996,"food, restaurant, order, india, service, user,..."
6,6.0,1.0,0.9996,"user, kerala, piggybank, flood, help, also, do..."
7,7.0,4.0,0.9992,"food, restaurant, order, india, service, user,..."
8,8.0,4.0,0.9597,"food, restaurant, order, india, service, user,..."
9,9.0,4.0,0.6255,"food, restaurant, order, india, service, user,..."
10,10.0,4.0,0.9995,"food, restaurant, order, india, service, user,..."
11,11.0,4.0,0.9997,"food, restaurant, order, india, service, user,..."
12,12.0,4.0,0.7523,"food, restaurant, order, india, service, user,..."
13,13.0,2.0,0.8155,"food, restaurant, hygiene, like, different, pl..."
14,14.0,4.0,0.9997,"food, restaurant, order, india, service, user,..."
15,15.0,4.0,0.9997,"food, restaurant, order, india, service, user,..."
16,16.0,2.0,0.9992,"food, restaurant, hygiene, like, different, pl..."
17,17.0,5.0,0.9427,"r, gb, india, new, ₹, phone, app, core, percen..."
18,18.0,4.0,0.9876,"food, restaurant, order, india, service, user,..."
19,19.0,5.0,0.8045,"r, gb, india, new, ₹, phone, app, core, percen..."
20,20.0,2.0,0.8218,"food, restaurant, hygiene, like, different, pl..."
21,21.0,5.0,0.8550,"r, gb, india, new, ₹, phone, app, core, percen..."
22,22.0,4.0,0.9994,"food, restaurant, order, india, service, user,..."

'Get Topic Modelling Results for-swgy_during_incdnt_topicmdl'

LDA Model topics output from Corpus[Latent Dirichlet Allocation Method] for:swgy_during_incdnt_topicmdl

[(0,
  '0.038*"order" + 0.030*"number" + 0.030*"partner" + 0.026*"post" + 0.022*"blog" + 0.022*"restaurant" + 0.018*"volume" + 0.018*"startup" + 0.018*"employee" + 0.013*"december"'),
 (1,
  '0.007*"reference" + 0.007*"regarding" + 0.007*"post" + 0.007*"present" + 0.007*"presentation" + 0.007*"published" + 0.007*"raised" + 0.007*"recent" + 0.007*"per" + 0.007*"responding"'),
 (2,
  '0.007*"reference" + 0.007*"regarding" + 0.007*"post" + 0.007*"present" + 0.007*"presentation" + 0.007*"published" + 0.007*"raised" + 0.007*"recent" + 0.007*"per" + 0.007*"responding"'),
 (3,
  '0.007*"reference" + 0.007*"regarding" + 0.007*"post" + 0.007*"present" + 0.007*"presentation" + 0.007*"published" + 0.007*"raised" + 0.007*"recent" + 0.007*"per" + 0.007*"responding"'),
 (4,
  '0.007*"post" + 0.007*"partner" + 0.007*"order" + 0.007*"recent" + 0.007*"present" + 0.007*"presentation" + 0.007*"published" + 0.007*"raised" + 0.007*"platform" + 0.007*"reference"')]

Gamma Matrix for: swgy_during_incdnt_topicmdl

    topic01  topic02  topic03  topic04  topic05
0  0.999945        0        0        0        0

Document Occurrence in Topics (A document in multiple topics) in: swgy_during_incdnt_topicmdl

,cnt_of_topics_doc_appeared,documents,tokens
0,1,"After hours of ""anxiety and confusion,"" online...","[hour, anxiety, confusion, online, food, start..."

Documents with dominant topic and its percentage contribution in: swgy_during_incdnt_topicmdl

,Doc_num,Dominant_Topic,Perc_Contribution,Topic_Keywords
0,0.0,1.0,0.9999,"order, number, partner, post, blog, restaurant..."

'Get Topic Modelling Results for-swgy_after_incdnt_topicmdl'

LDA Model topics output from Corpus[Latent Dirichlet Allocation Method] for:swgy_after_incdnt_topicmdl

[(0,
  '0.013*"sunder" + 0.010*"ai" + 0.008*"city" + 0.007*"team" + 0.007*"year" + 0.006*"vivek" + 0.006*"added" + 0.005*"u" + 0.005*"launch" + 0.005*"role"'),
 (1,
  '0.015*"food" + 0.014*"say" + 0.013*"restaurant" + 0.012*"order" + 0.011*"daga" + 0.010*"zomato" + 0.009*"freshmenu" + 0.009*"also" + 0.008*"like" + 0.008*"one"'),
 (2,
  '0.021*"food" + 0.014*"restaurant" + 0.014*"consumer" + 0.014*"partner" + 0.009*"service" + 0.008*"platform" + 0.008*"also" + 0.008*"million" + 0.007*"india" + 0.007*"ceo"'),
 (3,
  '0.013*"food" + 0.012*"r" + 0.012*"zomato" + 0.010*"roughly" + 0.008*"based" + 0.008*"crore" + 0.008*"india" + 0.008*"billion" + 0.008*"app" + 0.007*"ant"'),
 (4,
  '0.013*"month" + 0.013*"food" + 0.011*"super" + 0.010*"partner" + 0.010*"user" + 0.009*"experience" + 0.009*"data" + 0.009*"restaurant" + 0.008*"may" + 0.008*"customer"')]

Gamma Matrix for: swgy_after_incdnt_topicmdl

     topic01   topic02   topic03   topic04   topic05
0   0.000000  0.013253  0.985926  0.000000  0.000000
1   0.395018  0.000000  0.000000  0.000000  0.602725
2   0.000000  0.000000  0.000000  0.999572  0.000000
3   0.000000  0.000000  0.269563  0.729593  0.000000
4   0.000000  0.000000  0.781614  0.000000  0.217900
5   0.446163  0.045606  0.000000  0.507383  0.000000
6   0.000000  0.046546  0.000000  0.952019  0.000000
7   0.000000  0.030586  0.000000  0.968323  0.000000
8   0.539858  0.133635  0.300438  0.025657  0.000000
9   0.000000  0.000000  0.861648  0.000000  0.137443
10  0.000000  0.000000  0.000000  0.022404  0.976822
11  0.603762  0.000000  0.395054  0.000000  0.000000
12  0.000000  0.000000  0.730762  0.268788  0.000000
13  0.000000  0.886043  0.000000  0.113578  0.000000
14  0.000000  0.000000  0.329395  0.670096  0.000000
15  0.000000  0.000000  0.659013  0.340449  0.000000
16  0.000000  0.999317  0.000000  0.000000  0.000000
17  0.000000  0.030514  0.968647  0.000000  0.000000
18  0.000000  0.999305  0.000000  0.000000  0.000000
19  0.000000  0.999569  0.000000  0.000000  0.000000
20  0.000000  0.817803  0.000000  0.043781  0.138202

Document Occurrence in Topics (A document in multiple topics) in: swgy_after_incdnt_topicmdl

,cnt_of_topics_doc_appeared,documents,tokens
0,2,Homegrown food delivery start-up Swiggy on Mon...,"[homegrown, food, start, monday, launched, dai..."
1,2,"Swiggy, domestic online food ordering and deli...","[domestic, online, food, ordering, platform, s..."
2,1,Suraj Nachre works long hours and regularly mi...,"[suraj, nachre, work, long, hour, regularly, m..."
3,2,Indian online food delivery service Swiggy sai...,"[indian, online, food, service, tuesday, expan..."
4,2,Driven by a surge in online food orders especi...,"[driven, surge, online, food, order, especiall..."
5,3,Online food ordering and delivery app Swiggy o...,"[online, food, ordering, app, monday, announce..."
6,2,Online food delivery service provider Swiggy s...,"[online, food, service, provider, raised, bill..."
7,2,Diwali 2018 is just around the corner and Appl...,"[diwali, around, corner, apple, announced, off..."
8,4,"Food ordering and delivery platform, Swiggy on...","[food, ordering, platform, monday, announced, ..."
9,2,Indian online food ordering and delivery platf...,"[indian, online, food, ordering, platform, thu..."
10,2,"Swiggy, one of India's largest food ordering a...","[one, india, largest, food, ordering, platform..."
11,2,Swiggy on Monday announced appointment of Vive...,"[monday, announced, appointment, vivek, sunder..."
12,2,Swiggy on Thursday announced Series G funding ...,"[thursday, announced, series, g, funding, led,..."
13,2,"A few years ago, people were starting to write...","[year, ago, people, starting, write, food, ind..."
14,2,A unit of China's Alibaba Group Holding has in...,"[unit, china, alibaba, group, holding, investe..."
15,2,Swiggy on Thursday announced Series F funding ...,"[thursday, announced, series, f, funding, exis..."
16,1,Having choice is a good thing. That applies to...,"[choice, good, thing, applies, everything, air..."
17,2,Online food ordering and delivery platform Swi...,"[online, food, ordering, platform, tuesday, an..."
18,1,Zomato on Wednesday announced that it has comp...,"[zomato, wednesday, announced, completed, acqu..."
19,1,Food delivery has seen its ups and downs over ...,"[food, seen, ups, down, last, year, spate, com..."
20,3,"For companies that deliver your food, every se...","[company, deliver, food, every, second, precio..."

Documents with dominant topic and its percentage contribution in: swgy_after_incdnt_topicmdl

,Doc_num,Dominant_Topic,Perc_Contribution,Topic_Keywords
0,0.0,3.0,0.9859,"food, restaurant, consumer, partner, service, ..."
1,1.0,5.0,0.6027,"month, food, super, partner, user, experience,..."
2,2.0,4.0,0.9996,"food, r, zomato, roughly, based, crore, india,..."
3,3.0,4.0,0.7296,"food, r, zomato, roughly, based, crore, india,..."
4,4.0,3.0,0.7816,"food, restaurant, consumer, partner, service, ..."
5,5.0,4.0,0.5074,"food, r, zomato, roughly, based, crore, india,..."
6,6.0,4.0,0.9520,"food, r, zomato, roughly, based, crore, india,..."
7,7.0,4.0,0.9683,"food, r, zomato, roughly, based, crore, india,..."
8,8.0,1.0,0.5399,"sunder, ai, city, team, year, vivek, added, u,..."
9,9.0,3.0,0.8616,"food, restaurant, consumer, partner, service, ..."
10,10.0,5.0,0.9768,"month, food, super, partner, user, experience,..."
11,11.0,1.0,0.6038,"sunder, ai, city, team, year, vivek, added, u,..."
12,12.0,3.0,0.7308,"food, restaurant, consumer, partner, service, ..."
13,13.0,2.0,0.8860,"food, say, restaurant, order, daga, zomato, fr..."
14,14.0,4.0,0.6701,"food, r, zomato, roughly, based, crore, india,..."
15,15.0,3.0,0.6590,"food, restaurant, consumer, partner, service, ..."
16,16.0,2.0,0.9993,"food, say, restaurant, order, daga, zomato, fr..."
17,17.0,3.0,0.9686,"food, restaurant, consumer, partner, service, ..."
18,18.0,2.0,0.9993,"food, say, restaurant, order, daga, zomato, fr..."
19,19.0,2.0,0.9996,"food, say, restaurant, order, daga, zomato, fr..."
20,20.0,2.0,0.8178,"food, say, restaurant, order, daga, zomato, fr..."

'Get Topic Modelling Results for-swgy_before_incdnt_topicmdl'

LDA Model topics output from Corpus[Latent Dirichlet Allocation Method] for:swgy_before_incdnt_topicmdl

[(0,
  '0.019*"friend" + 0.012*"app" + 0.011*"people" + 0.010*"time" + 0.010*"one" + 0.009*"search" + 0.009*"fun" + 0.009*"plan" + 0.008*"game" + 0.007*"place"'),
 (1,
  '0.015*"restaurant" + 0.013*"foodpanda" + 0.011*"o" + 0.010*"say" + 0.009*"order" + 0.009*"also" + 0.009*"service" + 0.008*"system" + 0.008*"bali" + 0.007*"using"'),
 (2,
  '0.021*"r" + 0.016*"funding" + 0.014*"startup" + 0.014*"partner" + 0.011*"based" + 0.011*"venture" + 0.010*"raised" + 0.008*"round" + 0.008*"million" + 0.008*"crore"'),
 (3,
  '0.016*"food" + 0.015*"kitchen" + 0.014*"cloud" + 0.009*"company" + 0.008*"restaurant" + 0.007*"model" + 0.007*"also" + 0.005*"bowl" + 0.005*"option" + 0.004*"business"'),
 (4,
  '0.012*"fitness" + 0.010*"r" + 0.008*"gym" + 0.007*"new" + 0.007*"fitpass" + 0.006*"month" + 0.005*"user" + 0.005*"around" + 0.005*"funding" + 0.005*"people"')]

Gamma Matrix for: swgy_before_incdnt_topicmdl

     topic01   topic02   topic03   topic04   topic05
0   0.000000  0.000000  0.000000  0.000000  0.999858
1   0.000000  0.000000  0.999659  0.000000  0.000000
2   0.000000  0.839539  0.160196  0.000000  0.000000
3   0.000000  0.115019  0.000000  0.884866  0.000000
4   0.000000  0.000000  0.000000  0.000000  0.999880
5   0.324378  0.000000  0.675469  0.000000  0.000000
6   0.000000  0.047553  0.952224  0.000000  0.000000
7   0.000000  0.999883  0.000000  0.000000  0.000000
8   0.999950  0.000000  0.000000  0.000000  0.000000
9   0.963211  0.036531  0.000000  0.000000  0.000000
10  0.000000  0.000000  0.999803  0.000000  0.000000
11  0.000000  0.999897  0.000000  0.000000  0.000000

Document Occurrence in Topics (A document in multiple topics) in: swgy_before_incdnt_topicmdl

,cnt_of_topics_doc_appeared,documents,tokens
0,1,"Another day, another OnePlus 5 leak. This time...","[another, day, another, oneplus, leak, time, i..."
1,1,Online food delivery platform Swiggy on Tuesda...,"[online, food, platform, tuesday, raised, mill..."
2,2,Food ordering and delivery service Swiggy on T...,"[food, ordering, service, tuesday, announced, ..."
3,2,Online food delivery is a tricky business and ...,"[online, food, tricky, business, company, cont..."
4,1,"Around 18 months ago, a slew of fitness wearab...","[around, month, ago, slew, fitness, wearable, ..."
5,2,The demonetisation of 1000 Rs. and 500 Rs. not...,"[demonetisation, r, r, note, prime, minister, ..."
6,2,Food delivery platform Swiggy has appointed My...,"[food, platform, appointed, myntra, co, founde..."
7,1,One of the plus points of using a food deliver...,"[one, plus, point, using, food, app, explore, ..."
8,1,We've all been there - you start off with some...,"[start, email, meeting, friend, people, roped,..."
9,2,There might be many who have started using opt...,"[might, many, started, using, optimised, apps,..."
10,1,Funding activity seems to have increased in th...,"[funding, activity, seems, increased, week, fo..."
11,1,The food-tech industry is an increasingly comp...,"[food, tech, industry, increasingly, complex, ..."

Documents with dominant topic and its percentage contribution in: swgy_before_incdnt_topicmdl

,Doc_num,Dominant_Topic,Perc_Contribution,Topic_Keywords
0,0.0,5.0,0.9999,"fitness, r, gym, new, fitpass, month, user, ar..."
1,1.0,3.0,0.9997,"r, funding, startup, partner, based, venture, ..."
2,2.0,2.0,0.8395,"restaurant, foodpanda, o, say, order, also, se..."
3,3.0,4.0,0.8849,"food, kitchen, cloud, company, restaurant, mod..."
4,4.0,5.0,0.9999,"fitness, r, gym, new, fitpass, month, user, ar..."
5,5.0,3.0,0.6755,"r, funding, startup, partner, based, venture, ..."
6,6.0,3.0,0.9522,"r, funding, startup, partner, based, venture, ..."
7,7.0,2.0,0.9999,"restaurant, foodpanda, o, say, order, also, se..."
8,8.0,1.0,0.9999,"friend, app, people, time, one, search, fun, p..."
9,9.0,1.0,0.9632,"friend, app, people, time, one, search, fun, p..."
10,10.0,3.0,0.9998,"r, funding, startup, partner, based, venture, ..."
11,11.0,2.0,0.9999,"restaurant, foodpanda, o, say, order, also, se..."

In [5]:
#References:
#https://radimrehurek.com/gensim/models/ldamodel.html
#https://spacy.io/usage/models
#https://www.mdpi.com/2073-8994/11/12/1486/htm